import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import Footer from '@/components/Footer/footerIndex'
import Logo from '@/components/Logo/logoIndex'
import LoginForm from '@/components/Login/LoginIndex'


export default function Home() {
  return (
    <>
      <Head>
        <title>Twitter Login Layout</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="@/style/styles.css" />
      </Head>
      <main className={`${styles.main} ${styles.mainContainer}`}>
        <div className={styles.leftContainer}>
          <Logo/>
        </div>
        <div className={styles.rightContainer}>
          <LoginForm/>
        </div>
      </main>
      <footer className={styles.footerContainer}>
        <Footer/>
      </footer>
    </>
  )
}
